/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasresponsi;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HashU
 */
public class booking extends javax.swing.JFrame {

    koneksi x;
    DefaultTableModel tabmode;
    ArrayList<String> jam_mulai = new ArrayList<>();
    ArrayList<String> jam_selesai = new ArrayList<>();

    /**
     * Creates new form booking
     */
    public booking() {
        initComponents();
        x = new koneksi();
        x.koneksi();
                datatable();

    }

    void terima(String inputstu, String inputfm, String inputhg, String inputkode) {
        tempatstudio.setText(inputstu);
        namafilm.setText(inputfm);
        txtharga.setText(inputhg);
        txtkodekursi.setText(inputkode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltayang = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        namafilm = new javax.swing.JTextField();
        tempatstudio = new javax.swing.JTextField();
        txtkodekursi = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        txtjammulai = new javax.swing.JTextField();
        txtjamselesai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtjumlahtiket = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totalharga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 235, 235));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INDOXXS");
        jLabel1.setOpaque(true);

        jLabel2.setText("NAMA FILM");

        jLabel3.setText("STUDIO");

        jLabel4.setText("TEMPAT DUDUK");

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("booking");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("UNBOOK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("HARGA");

        tbltayang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbltayang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltayangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbltayang);

        jLabel6.setText("JADWAL");

        txtjammulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjammulaiActionPerformed(evt);
            }
        });

        jLabel7.setText("JUMLAH TIKET");

        txtjumlahtiket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjumlahtiketKeyReleased(evt);
            }
        });

        jLabel8.setText("TOTAL");

        totalharga.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtjumlahtiket)
                    .addComponent(txtkodekursi)
                    .addComponent(txtjammulai)
                    .addComponent(namafilm)
                    .addComponent(tempatstudio)
                    .addComponent(txtharga)
                    .addComponent(txtjamselesai)
                    .addComponent(totalharga, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(50, 50, 50)
                        .addComponent(jButton1)
                        .addGap(51, 51, 51)
                        .addComponent(jButton3)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namafilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tempatstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtkodekursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtjammulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(txtjamselesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton2))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtjumlahtiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(totalharga))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void datatable() {
        Object[] Baris = {"jam mulai", "jam selesai"};
        tabmode = new DefaultTableModel(null, Baris);
        tbltayang.setModel(tabmode);
        String sql = "select * from jamtayang";
        try {
           java.sql.Statement st = x.conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                jam_mulai.clear();
                jam_selesai.clear();
                
                int index = 0;
                
//                menambahkan data ke array list dengan data seperti didatabase
                jam_mulai.add(rs.getString("jam_mulai"));
                jam_selesai.add(rs.getString("jam_selesai"));                
//                menampulkan data dari array list
                String data[] = {jam_mulai.get(index), jam_selesai.get(index)};
                tabmode.addRow(data);
                index++;
            }
        } catch (Exception e) {

        }}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        studio kirim = new studio();
        kirim.terima(tempatstudio.getText(), namafilm.getText(), txtharga.getText());
        kirim.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String film, studio, kodekursi, harga, sql;
        film = namafilm.getText();
        studio = tempatstudio.getText();
        kodekursi = txtkodekursi.getText();
        harga = txtharga.getText();
        sql = "INSERT INTO bioskop(kodekursi, film, studio, harga) VALUES ('" + kodekursi + "', '" + film + "', '" + studio + "','" + harga + "')";

        try {
            x.st = x.conn.createStatement();
            x.st.execute(sql);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "sudah dibooking sebelumnya");
            return;
        }
        JOptionPane.showMessageDialog(null, "berhasil di booking");
        menuutama main = new menuutama();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String film, studio, kodekursi, harga, sql;
        film = namafilm.getText();
        studio = tempatstudio.getText();
        kodekursi = txtkodekursi.getText();
        harga = txtharga.getText();

        // sql = "delete from bioskop where kodeKursi='"+kodekursi+"'";
        sql = "delete from bioskop where kodeKursi='" + kodekursi + "'";
        try {
            x.st = x.conn.createStatement();
            x.st.execute(sql);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "gagal");
            return;
        }
        JOptionPane.showMessageDialog(null, "berhasil di unbooking");
        menuutama main = new menuutama();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbltayangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltayangMouseClicked
        // TODO add your handling code here:
        int baris = tbltayang.getSelectedRow();

        String datajam_mulai = tabmode.getValueAt(baris, 0).toString();
        String datajam_selesai = tabmode.getValueAt(baris, 1).toString();

        txtjammulai.setText(datajam_mulai);
        txtjamselesai.setText(datajam_selesai);
    }//GEN-LAST:event_tbltayangMouseClicked

    private void txtjammulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjammulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjammulaiActionPerformed

    private void txtjumlahtiketKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahtiketKeyReleased
        // TODO add your handling code here:
        if(txtjumlahtiket.getText().equals(""))
   {
       totalharga.setText("0");
   }
   else
   {
//       jika jumlah tiket ada isinya maka total bayar ada isinya
        String jumlah = txtjumlahtiket.getText();
    String harga = txtharga.getText();
    
    int total = Integer.parseInt(harga) * Integer.parseInt(jumlah);
//    System.out.println(total);
    
    String total_bayar = Integer.toString(total);
    
    totalharga.setText(total_bayar);
   }
    }//GEN-LAST:event_txtjumlahtiketKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namafilm;
    private javax.swing.JTable tbltayang;
    private javax.swing.JTextField tempatstudio;
    private javax.swing.JLabel totalharga;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjammulai;
    private javax.swing.JTextField txtjamselesai;
    private javax.swing.JTextField txtjumlahtiket;
    private javax.swing.JTextField txtkodekursi;
    // End of variables declaration//GEN-END:variables
}
